name: Pierre-Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: pierre-review
        uses: aummo/pierre-review@0.0.13b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_APP_PKEY: ${{ secrets.GH_APP_PKEY }}
          PIERRE_LANGCHAIN_LLM_API_TOKEN: ${{ secrets.PIERRE_LANGCHAIN_LLM_API_TOKEN }}
          PIERRE_LANGCHAIN_LLM_API_NAME: ${{ secrets.PIERRE_LANGCHAIN_LLM_API_NAME }}
