name: Pierre-Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PKEY }}
      - name: pierre-review
        uses: aummo/pierre-review@0.0.13c
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          PIERRE_LANGCHAIN_LLM_API_TOKEN: ${{ secrets.PIERRE_LANGCHAIN_LLM_API_TOKEN }}
          PIERRE_LANGCHAIN_LLM_API_NAME: ${{ secrets.PIERRE_LANGCHAIN_LLM_API_NAME }}
